# Basic
title: 张科的技术博客
subtitle: 折腾是一种态度
description: 嗨，我是张科(@GarfieldLover)，搜狐视频iOS开发者。
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 项目, url: 'http://project.o.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: GarfieldLover
    github: GarfieldLover
    stackoverflow: GarfieldLover
    douban: GarfieldLover
    twitter: GarfieldLover
    mail: zhangke19880503@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
